# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T438MVMUfhEkCzwzCx0JLAP9vbxNmFzY
"""

import streamlit as st
from nlp_models.translation import translate_text
from nlp_models.sentiment import sentiment_analysis
from nlp_models.classification import classify_text
from nlp_models.summarization import summarize_text

st.set_page_config(page_title="NLP Toolkit", layout="wide")
st.title("🧠 NLP Toolkit")

option = st.sidebar.selectbox(
    "Choose an NLP Task",
    [
        "Sentiment Analysis",
        "Text Classification",
        "Text Summarization",
        "Text Translation"
    ]
)

if option == "Sentiment Analysis":
    st.header("🔍 Sentiment Analysis")
    user_input = st.text_input("Enter a comment to analyze its sentiment")
    if st.button("Analyze Sentiment") and user_input:
        result = sentiment_analysis(user_input)
        st.success(f"Sentiment: {result}")

elif option == "Text Classification":
    st.header("🗂️ Text Classification")
    user_input = st.text_input("Enter text to classify")
    if st.button("Classify Text") and user_input:
        result = classify_text(user_input)
        st.success(f"Predicted Category: {result}")

elif option == "Text Summarization":
    st.header("📄 Text Summarization")
    user_input = st.text_area("Paste text (up to 600–700 words)", height=300)
    if st.button("Summarize") and user_input:
        result = summarize_text(user_input)
        st.success("Summary:")
        st.write(result)

elif option == "Text Translation":
    st.header("🌍 Text Translation")
    supported_languages = ["english", "hindi", "tamil", "telugu", "malayalam", "kannada", "japanese", "spanish", "french"]

    src_lang = st.selectbox("Select Source Language", supported_languages)
    tgt_lang = st.selectbox("Select Target Language", supported_languages)
    user_input = st.text_area("Enter text to translate")
    if st.button("Translate") and user_input:
        result = translate_text(user_input, src_lang, tgt_lang)
        st.success("Translated Text:")
        st.write(result)

