# -*- coding: utf-8 -*-
"""classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ex3ZV1w2LkFAJqYEmpDlgChpZFMCeudu
"""

# nlp_models/classification.py
from transformers import pipeline

# Use zero-shot classification with predefined labels
classifier = pipeline("zero-shot-classification")

# Define your categories
LABELS = ["sports", "technology", "politics", "entertainment", "science", "health"]

def classify_text(text):
    result = classifier(text, LABELS)
    return f"{result['labels'][0]} (confidence: {round(result['scores'][0], 2)})"

