# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnn5xO-xYpOrr7Uc9sf_ALYrMkWyzSQ7
"""

# nlp_models/sentiment.py
from transformers import pipeline

# Load the sentiment analysis pipeline once
sentiment_model = pipeline("sentiment-analysis")

def sentiment_analysis(text):
    result = sentiment_model(text)[0]
    return f"{result['label']} (confidence: {round(result['score'], 2)})"

